name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Client
        run: mvn -B package -DskipTests --file client/pom.xml
      - name: Build Client
        run: mvn -B package -DskipTests --file server/pom.xml
